name: Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # 2.0.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            registry.npmjs.org:443
            registry.yarnpkg.com:443

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
        with:
          persist-credentials: false
          token: ${{ secrets.SEMANTIC_RELEASE_PAT }}

      # we only need the two install-steps as long we have husky running as prepare script (which runs on publish)
      - name: Install Node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # 3.8.1
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@8e58d20d0f6c8773181f43eb74d6a05e3099571d # 3.4.2
        id: semantic
        with:
          semantic_version: 19.0.2
          branch: main
          extends: |
            @rweich/semantic-release-config
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Outputs
        run: |
          cat <<EOO >> $GITHUB_STEP_SUMMARY
            ---

            ### Semantic release output

            <table>
              <tr><th>published</th><td>${{ steps.semantic.outputs.new_release_published }}</td></tr>
              <tr><th>last release</th><td>${{ steps.semantic.outputs.last_release_version }}</td></tr>
              <tr><th>next release</th><td>${{ steps.semantic.outputs.new_release_version }}</td></tr>
            </table>

            ---

            #### Release-Notes

            ${{ steps.semantic.outputs.new_release_notes }}

          ---
          EOO
